### ISSUE TITLE
Power for robot is unsatisfactory, at best

### ISSUE THREAD

**Issue by Shane-Wood-TL** [Shane-Wood-TL/SW-Quadruped#11]
The current design of the bot uses a 65-watt USB C power bank and a USB PD breakout board to deliver 65W at 20V to the main buck converter. While this works it is far from ideal. The powerbank is heavy, a majority of the weight of the bot itself which is putting more strain on the motors. The USB PD board is not acceptable considering the amount of heat it outputs, leading to more energy loss.

**Comment by Townlake101** [comment]
There is currently a plan to switch over to some form of power tool battery to stop using the USB PD board as it gets far hotter than a component in spec should. This switch would also add a fuse leading to some actual safety measures in the bot.

However, this switch is going to be costly so it will not happen until the limits of the 65W battery have been reached.

**Comment by Shane-Wood-TL** [comment]
Battery conversion has been completed, BOM needs to be updated
