### ISSUE TITLE
Mainboard Issues

### ISSUE THREAD

**Issue by Shane-Wood-TL** [Shane-Wood-TL/SW-Quadruped#7]
The mainboard is missing a good 3V3 volt source (taking power from ESP32 is not advisable) Next PCB should have a 3v3 volt regulator. Along with this, the I2C bus needs to be fully converted to 3V3 as the PCA9685's are still currently on a 5V setup which could damage the ESP32.

Along with this, a spot for the NRF2401 should be added to the PCB since it is the radio that is used.

**Comment by Townlake101** [comment]
The new PCB version (not pushed yet) has a 3v3 regulator on board and a spot for the NRF2401 with a capacitor in place. It also switches the PCA9685s to 3v3

**Comment by Shane-Wood-TL** [comment]
This issue has been fully resolved with the current pcb
